[project]
name = "toolsz"
version = "0.1.4"
description = "负责工具"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dill>=0.3.9",
    "pytest>=8.3.5",
    "pytest-html>=4.1.1",
    "requests>=2.32.3",
    "setproctitle>=1.3.5",
    "setuptools>=78.1.0",
]
